name: Deploy

on:
    release:
        types: [published]

jobs:
    deploy-image:

        runs-on: ubuntu-22.04

        permissions:
            contents: read

        steps:
            -   name: Deploy the new images
                uses: appleboy/ssh-action@v1.0.3
                with:
                    host: ${{ secrets.SSH_HOST }}
                    username: ${{ secrets.SSH_USERNAME }}
                    password: ${{ secrets.SSH_PASSWORD }}
                    script: |
                        cd ~/coulba
                        docker stack deploy -c docker-compose.yml --with-registry-auth coulba
